### PR TITLE
removed castclass and introduced callvirt as a possible performance increaser - not sure about the safety ?

### PR DESCRIPTION
**Pull request by Danielovich**
From the CIL standard:

"The callvirt instruction calls a late-bound method on an object. That is, the method is chosen
based on the exact type". And since the type is known at this point in the code we can call it - that's at least how interpret it.

When I ran this on my machine it produced faster times than the original IL implementation. Please try it out if interested :)

### CODE REVIEW

**Comment by Danielovich** [comment]
on a different note, I don't know if you explicitly wanted to have CastClass in there ?

**Comment by mookid8000** [comment]
Hey @Danielovich , thanks for contributing 🙂 I just tried your modded IL invoker, and it is indeed a little bit faster! Here's how the runs went on my machine:

```
    New run with expression-based invoker (this time in Release mode):

SCOPE 'Dispatch 1000 commands' completed in 30,0883 ms | 0,030088300000000002 ms/item | 33,23551014846302 items/ms
SCOPE 'Dispatch 1000000 commands' completed in 2730,8531 ms | 0,0027308530999999997 ms/item | 366,18593654854595 items/ms
SCOPE 'Dispatch 10000000 commands' completed in 23148,3344 ms | 0,00231483344 ms/item | 431,9965241214072 items/ms
    
    New run with Danielovich's modded IL invoker (also in Release mode):

SCOPE 'Dispatch 1000 commands' completed in 38,6496 ms | 0,0386496 ms/item | 25,873488988243086 items/ms
SCOPE 'Dispatch 1000000 commands' completed in 2650,4597 ms | 0,0026504596999999998 ms/item | 377,29304090154625 items/ms
SCOPE 'Dispatch 10000000 commands' completed in 22555,6927 ms | 0,00225556927 ms/item | 443,34705801343 items/ms

```

I'd love to merge it, but I need you to sign the CLA.... or if you already did, I need you to figure out how you can tell GitHub that your commit was in fact committed by you. Usually, this can be done simply by adding the email address from the commit to your GitHub profile as an extra email address.

**Comment by Danielovich** [comment]
CLA was hanging due to email inconsistencies.

**Comment by mookid8000** [comment]
Beautiful ❤️ thanks! 🙂

**Comment by mookid8000** [comment]
It's out on NuGet.org as v. 0.0.22 now 🎉

**Pull request merged**
